### ISSUE TITLE
missing directories

### ISSUE THREAD

**Issue by talhakanyilmaz** [ozaerden/kanban-board#1]

**Comment by talhakanyilmaz** [comment]
@ozaerden js ve styles dizinleri eksik.

**Comment by ozaerden** [comment]
Kanki KendoUI kullaniyor firma, orda yazilmis bircok classlari var. Kendo’da jQuery ile suruklenebilir tablo var ama aynisini AngularJS ile yapmam lazim, koda oyle entegre edilecekmis. O yuzden bendeki gordugun o tabloyu suruklenebilir hale getiricem. GitHub’a atmadigim bi draggable list’im var yani, kodu siktir et kisacasi not defteri gibi tutuyorum 2-3 gune calisan halini cozebilirsem yuklerim :D
